from psdnipro.settings import DATABASES, STATICFILES_FINDERS


DATABASES['default']['USER'] = '{DB_USER}'
DATABASES['default']['PASSWORD'] = '{DB_PASSWORD'

STATICFILES_FINDERS.append('compressor.finders.CompressorFinder')


ADMINS = (
    ('{ADMIN_NAME}', '{ADMIN_EMAIL}'),
)
MANAGERS = ADMINS
EMAIL_HOST_USER = DEFAULT_FROM_EMAIL = '{PROJECT_EMAIL}'
EMAIL_HOST_PASSWORD = '{PROJECT_EMAIL_PASSWORD}'

COMPRESS_OFFLINE = True


ALLOWED_HOSTS = ['{SERVER_IP}', '.{SERVER_DOMAIN}', '.{SERVER_DOMAIN}.']
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 60 * 60  # 60 * 60 * 24 * 365
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True
X_FRAME_OPTIONS = 'DENY'
