# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 21:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name="Ім'я")),
                ('email', models.EmailField(max_length=254, verbose_name='Адреса електронної пошти')),
                ('message', models.TextField(verbose_name='Текст повідомлення')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата розміщення')),
            ],
            options={
                'verbose_name': 'повідомлення',
                'verbose_name_plural': 'Повідомлення',
            },
        ),
    ]
