# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='Ключ')),
                ('value', models.CharField(max_length=128, verbose_name='Значення')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('section', models.PositiveSmallIntegerField(choices=[(0, 'General')], verbose_name='Секція')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Текст'), (1, 'Ціле число'), (2, 'Десятковий дріб'), (3, 'Натуральний дріб')], verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Налаштування',
                'verbose_name_plural': 'Налаштування',
            },
        ),
    ]
