# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='section',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Загальне'), (1, 'Зовнішні посилання')], verbose_name='Секція'),
        ),
    ]
