# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 23:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua_string', models.TextField(blank=True, verbose_name='User-Agent')),
                ('ip', models.TextField(blank=True, db_index=True, verbose_name='IP адреса')),
                ('referrer', models.TextField(blank=True, verbose_name='URL джерела запиту')),
                ('browser_family', models.TextField(blank=True, db_index=True, verbose_name='Сімейство браузера')),
                ('browser_version', models.TextField(blank=True, verbose_name='Версія браузера')),
                ('os_family', models.TextField(blank=True, db_index=True, verbose_name='Сімейство операційної системи')),
                ('os_version', models.TextField(blank=True, verbose_name='Версія операційної системи')),
                ('device_brand', models.TextField(blank=True, db_index=True, verbose_name='Марка пристрою')),
                ('device_family', models.TextField(blank=True, verbose_name='Сімейство пристрою')),
                ('device_model', models.TextField(blank=True, verbose_name='Модель пристрою')),
                ('coordinates', models.TextField(blank=True, verbose_name='Координати')),
                ('city', models.TextField(blank=True, db_index=True, verbose_name='Місто')),
                ('region', models.TextField(blank=True, verbose_name='Регіон')),
                ('country', models.TextField(blank=True, db_index=True, verbose_name='Країна')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата розміщення')),
            ],
            options={
                'verbose_name': 'запис відстеження',
                'verbose_name_plural': 'Записи відстеження',
            },
        ),
    ]
