# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20151220_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='articles', to='news.Image', verbose_name='Додаткові зображення до статті'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_image',
            field=models.ForeignKey(blank=True, help_text='Якщо не обрано, за замовчуванням використовується <a href="/static/news/img/default-preview.png" target="_blank">стандартне зображення</a>.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_articles', to='news.Image', verbose_name='Основне зображення до статті'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(verbose_name='Текст новини'),
        ),
        migrations.AlterField(
            model_name='article',
            name='top_image',
            field=models.ForeignKey(blank=True, help_text='Оптимальний розмір - 727 x 378.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_articles', to='news.Image', verbose_name='Зображення для ТОПу'),
        ),
    ]
