# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20151220_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name="Ім'я")),
                ('position', models.CharField(max_length=128, verbose_name='Посада')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Світлина')),
                ('bio', models.TextField(blank=True, verbose_name='Анкета')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='priority_order',
        ),
        migrations.AddField(
            model_name='teammember',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Category', verbose_name='Категорія'),
        ),
    ]
