# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20151228_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('phones', models.TextField()),
                ('is_active', models.BooleanField(default=True, verbose_name='Відображати?')),
            ],
            options={
                'verbose_name_plural': 'Контакти',
                'verbose_name': 'контакт',
            },
        ),
    ]
