# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 14:04
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields
import sortedm2m.operations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20160209_1444'),
    ]

    operations = [
        sortedm2m.operations.AlterSortedManyToManyField(
            model_name='teammember',
            name='categories',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='members', to='news.Category', verbose_name='Категорії'),
        ),
    ]
