# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 15:35
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20160220_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='members',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='categories', to='news.TeamMember', verbose_name='Персони'),
        ),
    ]
