# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 15:46
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20160220_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='document',
            name='category',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='is_active',
        ),
        migrations.AddField(
            model_name='category',
            name='documents',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='categories', to='news.Document', verbose_name='Документи'),
        ),
        migrations.AlterField(
            model_name='category',
            name='members',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='categories', to='news.TeamMember', verbose_name='Персони'),
        ),
    ]
