# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20160220_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='Якщо не обрано, буде використано стандартне зображення.', null=True, upload_to='uploads/', verbose_name='Основне зображення до статті'),
        ),
    ]
