# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20151221_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'запис персони', 'verbose_name_plural': 'Персони'},
        ),
    ]
