# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 00:28
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20151222_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='images',
        ),
        migrations.RemoveField(
            model_name='article',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='top_image',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='Якщо не обрано, за замовчуванням використовується <a href="/static/news/img/default-preview.png" target="_blank">стандартне зображення</a>.', null=True, upload_to='uploads/', verbose_name='Основне зображення до статті'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Відображати?'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст новини'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
