# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20151225_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('url', models.URLField(verbose_name='Посилання')),
                ('is_active', models.BooleanField(default=True, verbose_name='Відображати?')),
            ],
            options={
                'verbose_name_plural': 'Документи',
                'verbose_name': 'документ',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Відображати?'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Відображати?'),
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Category', verbose_name='Категорія'),
        ),
    ]
