# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20151228_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
    ]
